  # 应用服务 WEB 访问端口
  server:
      port: 8081
      servlet:
          context-path: /
  spring:
      datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/student?serverTimezone=GMT%2B8&&characterEncoding=utf8
          password: root
          username: root
      redis:
          password: 123456
          host: 127.0.0.1
          port: 6379
  mybatis:
      mapper-locations: classpath:mapper/*.xml