server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?student?serverTimezone=GMT%2B8&&characterEncoding=utf8
    password: root
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
